### ISSUE TITLE
Cublas runtime error when training network

### ISSUE THREAD

**Issue by elias-Mimetrik** [tolgabirdal/qecnetworks#11]
I downloaded and processed the _modelnet40_normal_resampled_ dataset as described in the file _dataset_preparation.ipynb_

Then I installed similar versions of the libraries used:
```
conda install pytorch==1.1.0 torchvision==0.3.0 cudatoolkit=10.0 -c pytorch
pip install tensorflow==1.14
pip install open3d pyquaternion scipy
```

I installed the modules:
```
cd models/pytorch-cusolver
python setup.py install
cd ../pytorch-autograd-solver
python setup.py install
```

Then I ran the training command:
`python train_cls.py --inter_out_channels 128 --num_iterations 3 --num_of_class 10 --num_gen_samples 5 --data_path '/home/elias/Downloads/modelnet40_normal_resampled/'`

The error I got was:

```
Namespace(batch_size=16, class_choice=None, data_path='/home/elias/Downloads/modelnet40_normal_resampled/', init_lr=0.001, inter_out_channels=128, model='', n_epochs=400, num_gen_samples=5, num_iterations=3, num_of_class=10, num_points=2048)
Traceback (most recent call last):
  File "train_cls.py", line 108, in <module>
    main()
  File "train_cls.py", line 62, in main
    pose_out, a_out= qec_net(points_pool1, lrfs_pool1,  activation_pool1, points_pool2_index)
  File "/home/elias/miniconda3/envs/QEC_Nets/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/elias/miniconda3/envs/QEC_Nets/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/elias/miniconda3/envs/QEC_Nets/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "models/qec_net.py", line 37, in forward
    pose_pool1, activation_pool1 = self.pool1(points4pool1, lrfs4pool1, activation4pool1)
  File "/home/elias/miniconda3/envs/QEC_Nets/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "models/qec_module.py", line 169, in forward
    mean_lrf, mean_lrf_inv=self.mean_lrf_per_patch(lrfs, activation)
  File "models/qec_module.py", line 104, in mean_lrf_per_patch
    mean_lrf=self.averageQuaternions(_input_lrf, input_a)
  File "models/qec_module.py", line 39, in averageQuaternions
    cov_matrix=torch.bmm(_input_lrf.unsqueeze(2),_input_lrf.unsqueeze(1))
RuntimeError: cublas runtime error : the GPU program failed to execute at /opt/conda/conda-bld/pytorch_1556653099582/work/aten/src/THC/THCBlas.cu:450
```

Any idea how to properly train the network please?

**Comment by dilaragokay** [comment]
Could it be due to a mismatch between your GPU and CUDA version? [This issue](https://github.com/pytorch/pytorch/issues/17334) could be relevant.
